[2022-08-08 00:05:48,679] {processor.py:163} INFO - Started process (PID=14938) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 00:05:48,701] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 00:05:48,712] {logging_mixin.py:109} INFO - [2022-08-08 00:05:48,712] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 00:05:54,980] {logging_mixin.py:109} INFO - [2022-08-08 00:05:54,965] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 00:05:55,083] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 00:05:55,133] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 6.481 seconds
[2022-08-08 00:11:27,714] {processor.py:163} INFO - Started process (PID=15011) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 00:11:27,741] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 00:11:27,755] {logging_mixin.py:109} INFO - [2022-08-08 00:11:27,753] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 00:11:58,524] {logging_mixin.py:109} INFO - [2022-08-08 00:11:58,237] {timeout.py:36} ERROR - Process timed out, PID: 15011
[2022-08-08 00:12:13,293] {logging_mixin.py:109} INFO - [2022-08-08 00:11:58,951] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 8, in <module>
    from airflow.providers.google.cloud.operators.bigquery import BigQueryCreateExternalTableOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 38, in <module>
    from airflow.providers.google.cloud.hooks.bigquery import BigQueryHook, BigQueryJob
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 33, in <module>
    from google.cloud.bigquery import (
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 61, in <module>
    from google.cloud.bigquery_storage_v1.services.big_query_read.client import (
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery_storage_v1/__init__.py", line 25, in <module>
    from google.cloud.bigquery_storage_v1 import client
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery_storage_v1/client.py", line 26, in <module>
    from google.cloud.bigquery_storage_v1 import reader
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery_storage_v1/reader.py", line 28, in <module>
    import pandas
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 50, in <module>
    from pandas.core.api import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/api.py", line 48, in <module>
    from pandas.core.groupby import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/__init__.py", line 1, in <module>
    from pandas.core.groupby.generic import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/groupby/generic.py", line 73, in <module>
    from pandas.core.frame import DataFrame
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/frame.py", line 129, in <module>
    from pandas.core import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 191, in <module>
    class NDFrame(PandasObject, indexing.IndexingMixin):
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 7725, in NDFrame
    offset: TimedeltaConvertibleTypes | None = None,
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 372, in decorator
    docstring_components.append(dedent(decorated.__doc__))
  File "/usr/local/lib/python3.7/textwrap.py", line 431, in dedent
    indents = _leading_whitespace_re.findall(text)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/gcs_to_bigquery.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 15011
[2022-08-08 00:37:51,388] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 00:37:51,622] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 1585.158 seconds
[2022-08-08 00:37:56,317] {processor.py:163} INFO - Started process (PID=15048) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 00:37:56,348] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 00:37:56,393] {logging_mixin.py:109} INFO - [2022-08-08 00:37:56,393] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 00:38:27,045] {logging_mixin.py:109} INFO - [2022-08-08 00:38:26,692] {timeout.py:36} ERROR - Process timed out, PID: 15048
[2022-08-08 00:38:34,527] {logging_mixin.py:109} INFO - [2022-08-08 00:38:27,414] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 8, in <module>
    from airflow.providers.google.cloud.operators.bigquery import BigQueryCreateExternalTableOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 38, in <module>
    from airflow.providers.google.cloud.hooks.bigquery import BigQueryHook, BigQueryJob
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 33, in <module>
    from google.cloud.bigquery import (
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 61, in <module>
    from google.cloud.bigquery_storage_v1.services.big_query_read.client import (
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery_storage_v1/__init__.py", line 25, in <module>
    from google.cloud.bigquery_storage_v1 import client
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery_storage_v1/client.py", line 26, in <module>
    from google.cloud.bigquery_storage_v1 import reader
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery_storage_v1/reader.py", line 28, in <module>
    import pandas
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/__init__.py", line 22, in <module>
    from pandas.compat import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/__init__.py", line 15, in <module>
    from pandas.compat.numpy import (
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/compat/numpy/__init__.py", line 7, in <module>
    from pandas.util.version import Version
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/__init__.py", line 1, in <module>
    from pandas.util._decorators import (  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 14, in <module>
    from pandas._libs.properties import cache_readonly  # noqa
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/_libs/__init__.py", line 13, in <module>
    from pandas._libs.interval import Interval
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1368, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1408, in _fill_cache
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/gcs_to_bigquery.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 15048
[2022-08-08 00:38:46,026] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 01:09:03,779] {processor.py:163} INFO - Started process (PID=15097) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 01:09:03,808] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 01:09:03,844] {logging_mixin.py:109} INFO - [2022-08-08 01:09:03,844] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 01:09:36,082] {logging_mixin.py:109} INFO - [2022-08-08 01:09:34,421] {timeout.py:36} ERROR - Process timed out, PID: 15097
[2022-08-08 01:09:43,336] {logging_mixin.py:109} INFO - [2022-08-08 01:09:36,632] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 7, in <module>
    from google.cloud import storage
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/__init__.py", line 35, in <module>
    from google.cloud.storage.batch import Batch
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/batch.py", line 29, in <module>
    from google.cloud import _helpers
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_helpers.py", line 37, in <module>
    import grpc
  File "/home/airflow/.local/lib/python3.7/site-packages/grpc/__init__.py", line 2189, in <module>
    from grpc import aio  # pylint: disable=ungrouped-imports
  File "/home/airflow/.local/lib/python3.7/site-packages/grpc/aio/__init__.py", line 42, in <module>
    from ._base_server import Server
  File "/home/airflow/.local/lib/python3.7/site-packages/grpc/aio/_base_server.py", line 28, in <module>
    class Server(abc.ABC):
  File "/home/airflow/.local/lib/python3.7/site-packages/grpc/aio/_base_server.py", line 34, in Server
    generic_rpc_handlers: Sequence[grpc.GenericRpcHandler]) -> None:
  File "/usr/local/lib/python3.7/typing.py", line 251, in inner
    return cached(*args, **kwds)
  File "/usr/local/lib/python3.7/typing.py", line 636, in __getitem__
    return _subs_tvars(self, self.__parameters__, params)
  File "/usr/local/lib/python3.7/typing.py", line 196, in _subs_tvars
    return tp.copy_with(tuple(new_args))
  File "/usr/local/lib/python3.7/typing.py", line 640, in copy_with
    return _GenericAlias(self.__origin__, params, name=self._name, inst=self._inst)
  File "/usr/local/lib/python3.7/typing.py", line 622, in __init__
    self.__slots__ = None  # This is not documented.
  File "/usr/local/lib/python3.7/typing.py", line 711, in __setattr__
    super().__setattr__(attr, val)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/gcs_to_bigquery.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 15097
[2022-08-08 01:10:56,193] {processor.py:163} INFO - Started process (PID=15140) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 01:10:57,215] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 01:10:58,085] {logging_mixin.py:109} INFO - [2022-08-08 01:10:57,939] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 01:11:30,701] {logging_mixin.py:109} INFO - [2022-08-08 01:11:30,698] {timeout.py:36} ERROR - Process timed out, PID: 15140
[2022-08-08 01:11:39,217] {logging_mixin.py:109} INFO - [2022-08-08 01:11:31,154] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 8, in <module>
    from airflow.providers.google.cloud.operators.bigquery import BigQueryCreateExternalTableOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 38, in <module>
    from airflow.providers.google.cloud.hooks.bigquery import BigQueryHook, BigQueryJob
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 33, in <module>
    from google.cloud.bigquery import (
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 61, in <module>
    from google.cloud.bigquery_storage_v1.services.big_query_read.client import (
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery_storage_v1/__init__.py", line 25, in <module>
    from google.cloud.bigquery_storage_v1 import client
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery_storage_v1/client.py", line 24, in <module>
    import google.api_core.gapic_v1.method
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/gapic_v1/__init__.py", line 26, in <module>
    from google.api_core.gapic_v1 import method_async  # noqa: F401
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/gapic_v1/method_async.py", line 20, in <module>
    from google.api_core import general_helpers, grpc_helpers_async
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/grpc_helpers_async.py", line 116, in <module>
    class _WrappedStreamRequestMixin(_WrappedCall):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/gcs_to_bigquery.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 15140
[2022-08-08 01:44:03,340] {processor.py:163} INFO - Started process (PID=15232) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 01:44:03,486] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 01:44:03,586] {logging_mixin.py:109} INFO - [2022-08-08 01:44:03,585] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 01:44:33,876] {logging_mixin.py:109} INFO - [2022-08-08 01:44:33,874] {timeout.py:36} ERROR - Process timed out, PID: 15232
[2022-08-08 01:44:34,318] {logging_mixin.py:109} INFO - [2022-08-08 01:44:33,954] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 8, in <module>
    from airflow.providers.google.cloud.operators.bigquery import BigQueryCreateExternalTableOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 37, in <module>
    from airflow.operators.sql import SQLCheckOperator, SQLIntervalCheckOperator, SQLValueCheckOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/sql.py", line 23, in <module>
    from airflow.hooks.base import BaseHook
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 101, in <module>
    class DiscoverableHook(Protocol):
  File "/usr/local/lib/python3.7/abc.py", line 126, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/typing_extensions.py", line 1536, in __init_subclass__
    cls._is_protocol = any(b is Protocol for b in cls.__bases__)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/gcs_to_bigquery.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 15232
[2022-08-08 01:44:35,585] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 01:44:36,325] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 35.852 seconds
[2022-08-08 01:45:22,160] {processor.py:163} INFO - Started process (PID=15272) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 01:45:25,512] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 01:45:27,001] {logging_mixin.py:109} INFO - [2022-08-08 01:45:26,820] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 02:01:11,870] {logging_mixin.py:109} INFO - [2022-08-08 02:01:11,826] {timeout.py:36} ERROR - Process timed out, PID: 15272
[2022-08-08 02:01:12,451] {logging_mixin.py:109} WARNING - Exception ignored in: <module 'collections.abc' from '/usr/local/lib/python3.7/collections/abc.py'>
[2022-08-08 02:01:12,463] {logging_mixin.py:109} WARNING - Traceback (most recent call last):
[2022-08-08 02:01:12,468] {logging_mixin.py:109} WARNING -   File "<string>", line 1, in <module>
[2022-08-08 02:01:12,489] {logging_mixin.py:109} WARNING -   File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
[2022-08-08 02:01:12,508] {logging_mixin.py:109} WARNING -     raise AirflowTaskTimeout(self.error_message)
[2022-08-08 02:01:12,519] {logging_mixin.py:109} WARNING - airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/gcs_to_bigquery.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 15272
[2022-08-08 02:01:20,180] {processor.py:163} INFO - Started process (PID=15304) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 02:01:20,200] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 02:01:20,295] {logging_mixin.py:109} INFO - [2022-08-08 02:01:20,295] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 02:01:50,947] {logging_mixin.py:109} INFO - [2022-08-08 02:01:50,509] {timeout.py:36} ERROR - Process timed out, PID: 15304
[2022-08-08 02:01:59,925] {logging_mixin.py:109} INFO - [2022-08-08 02:01:51,445] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 7, in <module>
    from google.cloud import storage
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/__init__.py", line 35, in <module>
    from google.cloud.storage.batch import Batch
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/batch.py", line 29, in <module>
    from google.cloud import _helpers
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_helpers.py", line 37, in <module>
    import grpc
  File "/home/airflow/.local/lib/python3.7/site-packages/grpc/__init__.py", line 2189, in <module>
    from grpc import aio  # pylint: disable=ungrouped-imports
  File "/home/airflow/.local/lib/python3.7/site-packages/grpc/aio/__init__.py", line 45, in <module>
    from ._channel import insecure_channel
  File "/home/airflow/.local/lib/python3.7/site-packages/grpc/aio/_channel.py", line 32, in <module>
    from ._interceptor import ClientInterceptor
  File "/home/airflow/.local/lib/python3.7/site-packages/grpc/aio/_interceptor.py", line 43, in <module>
    from ._utils import _timeout_to_deadline
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 828, in get_code
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/gcs_to_bigquery.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 15304
[2022-08-08 02:02:39,258] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 02:22:59,014] {processor.py:163} INFO - Started process (PID=15457) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 02:22:59,255] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 02:22:59,533] {logging_mixin.py:109} INFO - [2022-08-08 02:22:59,511] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 02:23:29,702] {logging_mixin.py:109} INFO - [2022-08-08 02:23:29,701] {timeout.py:36} ERROR - Process timed out, PID: 15457
[2022-08-08 02:23:30,111] {logging_mixin.py:109} INFO - [2022-08-08 02:23:29,989] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 7, in <module>
    from google.cloud import storage
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/__init__.py", line 36, in <module>
    from google.cloud.storage.blob import Blob
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/blob.py", line 48, in <module>
    from google.resumable_media.requests import ChunkedDownload
  File "/home/airflow/.local/lib/python3.7/site-packages/google/resumable_media/requests/__init__.py", line 663, in <module>
    from google.resumable_media.requests.upload import MultipartUpload
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/gcs_to_bigquery.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 15457
[2022-08-08 02:23:30,639] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 02:23:33,005] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 34.703 seconds
[2022-08-08 03:17:40,018] {processor.py:163} INFO - Started process (PID=15607) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 03:17:40,027] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 03:17:40,144] {logging_mixin.py:109} INFO - [2022-08-08 03:17:40,143] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 03:18:18,200] {logging_mixin.py:109} INFO - [2022-08-08 03:18:18,184] {timeout.py:36} ERROR - Process timed out, PID: 15607
[2022-08-08 03:18:18,275] {logging_mixin.py:109} INFO - [2022-08-08 03:18:18,209] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 7, in <module>
    from google.cloud import storage
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/__init__.py", line 35, in <module>
    from google.cloud.storage.batch import Batch
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/batch.py", line 31, in <module>
    from google.cloud.storage._http import Connection
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/_http.py", line 21, in <module>
    from google.cloud import _http
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http.py", line 30, in <module>
    from google.api_core.client_info import ClientInfo
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/client_info.py", line 31, in <module>
    _GRPC_VERSION = pkg_resources.get_distribution("grpcio").version
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 464, in get_distribution
    dist = Requirement.parse(dist)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3139, in parse
    req, = parse_requirements(s)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3084, in parse_requirements
    yield Requirement(line)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3094, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 98, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1635, in parseString
    ParserElement.resetCache()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/gcs_to_bigquery.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 15607
[2022-08-08 06:06:52,432] {processor.py:163} INFO - Started process (PID=47) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:06:52,436] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:06:52,459] {logging_mixin.py:109} INFO - [2022-08-08 06:06:52,448] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:06:59,645] {logging_mixin.py:109} INFO - [2022-08-08 06:06:59,636] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:06:59,689] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:06:59,722] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 7.345 seconds
[2022-08-08 06:07:30,142] {processor.py:163} INFO - Started process (PID=115) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:07:30,152] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:07:30,160] {logging_mixin.py:109} INFO - [2022-08-08 06:07:30,160] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:07:33,791] {logging_mixin.py:109} INFO - [2022-08-08 06:07:33,789] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:07:33,816] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:07:33,866] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 3.753 seconds
[2022-08-08 06:08:04,740] {processor.py:163} INFO - Started process (PID=178) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:08:04,743] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:08:04,745] {logging_mixin.py:109} INFO - [2022-08-08 06:08:04,744] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:08:05,446] {logging_mixin.py:109} INFO - [2022-08-08 06:08:05,444] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:08:05,465] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:08:05,474] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.737 seconds
[2022-08-08 06:08:36,074] {processor.py:163} INFO - Started process (PID=240) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:08:36,076] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:08:36,077] {logging_mixin.py:109} INFO - [2022-08-08 06:08:36,077] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:08:36,717] {logging_mixin.py:109} INFO - [2022-08-08 06:08:36,714] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:08:36,733] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:08:36,742] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.674 seconds
[2022-08-08 06:09:07,448] {processor.py:163} INFO - Started process (PID=302) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:09:07,452] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:09:07,454] {logging_mixin.py:109} INFO - [2022-08-08 06:09:07,454] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:09:08,128] {logging_mixin.py:109} INFO - [2022-08-08 06:09:08,125] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:09:08,142] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:09:08,152] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.710 seconds
[2022-08-08 06:09:38,775] {processor.py:163} INFO - Started process (PID=374) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:09:38,779] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:09:38,781] {logging_mixin.py:109} INFO - [2022-08-08 06:09:38,781] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:09:39,488] {logging_mixin.py:109} INFO - [2022-08-08 06:09:39,486] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:09:39,506] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:09:39,514] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.749 seconds
[2022-08-08 06:10:10,106] {processor.py:163} INFO - Started process (PID=436) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:10:10,109] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:10:10,111] {logging_mixin.py:109} INFO - [2022-08-08 06:10:10,110] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:10:10,771] {logging_mixin.py:109} INFO - [2022-08-08 06:10:10,768] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:10:10,788] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:10:10,798] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.698 seconds
[2022-08-08 06:10:41,308] {processor.py:163} INFO - Started process (PID=505) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:10:41,312] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:10:41,316] {logging_mixin.py:109} INFO - [2022-08-08 06:10:41,315] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:10:42,271] {logging_mixin.py:109} INFO - [2022-08-08 06:10:42,268] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:10:42,289] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:10:42,301] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.997 seconds
[2022-08-08 06:11:12,836] {processor.py:163} INFO - Started process (PID=569) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:11:12,839] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:11:12,840] {logging_mixin.py:109} INFO - [2022-08-08 06:11:12,840] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:11:13,472] {logging_mixin.py:109} INFO - [2022-08-08 06:11:13,469] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:11:13,488] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:11:13,497] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.665 seconds
[2022-08-08 06:11:44,394] {processor.py:163} INFO - Started process (PID=639) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:11:44,397] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:11:44,399] {logging_mixin.py:109} INFO - [2022-08-08 06:11:44,399] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:11:45,051] {logging_mixin.py:109} INFO - [2022-08-08 06:11:45,049] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:11:45,066] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:11:45,076] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.686 seconds
[2022-08-08 06:12:15,994] {processor.py:163} INFO - Started process (PID=700) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:12:15,997] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:12:15,999] {logging_mixin.py:109} INFO - [2022-08-08 06:12:15,999] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:12:16,663] {logging_mixin.py:109} INFO - [2022-08-08 06:12:16,661] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:12:16,681] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:12:16,693] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.702 seconds
[2022-08-08 06:12:46,825] {processor.py:163} INFO - Started process (PID=769) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:12:46,829] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:12:46,830] {logging_mixin.py:109} INFO - [2022-08-08 06:12:46,830] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:12:47,434] {logging_mixin.py:109} INFO - [2022-08-08 06:12:47,432] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:12:47,449] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:12:47,458] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.638 seconds
[2022-08-08 06:13:17,943] {processor.py:163} INFO - Started process (PID=830) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:13:17,946] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:13:17,948] {logging_mixin.py:109} INFO - [2022-08-08 06:13:17,948] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:13:18,552] {logging_mixin.py:109} INFO - [2022-08-08 06:13:18,550] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:13:18,567] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:13:18,577] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.638 seconds
[2022-08-08 06:13:48,741] {processor.py:163} INFO - Started process (PID=899) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:13:48,743] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:13:48,745] {logging_mixin.py:109} INFO - [2022-08-08 06:13:48,745] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:13:49,383] {logging_mixin.py:109} INFO - [2022-08-08 06:13:49,380] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:13:49,398] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:13:49,406] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.671 seconds
[2022-08-08 06:14:20,354] {processor.py:163} INFO - Started process (PID=959) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:14:20,357] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:14:20,358] {logging_mixin.py:109} INFO - [2022-08-08 06:14:20,358] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:14:21,092] {logging_mixin.py:109} INFO - [2022-08-08 06:14:21,090] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:14:21,121] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:14:21,134] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.784 seconds
[2022-08-08 06:14:51,212] {processor.py:163} INFO - Started process (PID=1029) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:14:51,215] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:14:51,217] {logging_mixin.py:109} INFO - [2022-08-08 06:14:51,217] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:14:51,855] {logging_mixin.py:109} INFO - [2022-08-08 06:14:51,852] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:14:51,872] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:14:51,882] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.675 seconds
[2022-08-08 06:15:22,410] {processor.py:163} INFO - Started process (PID=1091) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:15:22,413] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:15:22,415] {logging_mixin.py:109} INFO - [2022-08-08 06:15:22,414] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:15:23,057] {logging_mixin.py:109} INFO - [2022-08-08 06:15:23,055] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:15:23,082] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:15:23,091] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.686 seconds
[2022-08-08 06:15:53,797] {processor.py:163} INFO - Started process (PID=1160) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:15:53,799] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:15:53,800] {logging_mixin.py:109} INFO - [2022-08-08 06:15:53,800] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:15:54,416] {logging_mixin.py:109} INFO - [2022-08-08 06:15:54,414] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:15:54,433] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:15:54,441] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.647 seconds
[2022-08-08 06:16:25,275] {processor.py:163} INFO - Started process (PID=1220) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:16:25,278] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:16:25,280] {logging_mixin.py:109} INFO - [2022-08-08 06:16:25,280] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:16:25,995] {logging_mixin.py:109} INFO - [2022-08-08 06:16:25,993] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:16:26,013] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:16:26,026] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.758 seconds
[2022-08-08 06:16:56,885] {processor.py:163} INFO - Started process (PID=1298) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:16:56,888] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:16:56,890] {logging_mixin.py:109} INFO - [2022-08-08 06:16:56,889] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:16:57,513] {logging_mixin.py:109} INFO - [2022-08-08 06:16:57,511] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:16:57,529] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:16:57,539] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.659 seconds
[2022-08-08 06:17:28,027] {processor.py:163} INFO - Started process (PID=1359) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:17:28,030] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:17:28,032] {logging_mixin.py:109} INFO - [2022-08-08 06:17:28,031] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:17:28,660] {logging_mixin.py:109} INFO - [2022-08-08 06:17:28,658] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:17:28,678] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:17:28,690] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.667 seconds
[2022-08-08 06:17:58,798] {processor.py:163} INFO - Started process (PID=1431) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:17:58,802] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:17:58,804] {logging_mixin.py:109} INFO - [2022-08-08 06:17:58,803] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:17:59,538] {logging_mixin.py:109} INFO - [2022-08-08 06:17:59,536] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:17:59,560] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:17:59,573] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.778 seconds
[2022-08-08 06:18:29,968] {processor.py:163} INFO - Started process (PID=1492) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:18:29,971] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:18:29,973] {logging_mixin.py:109} INFO - [2022-08-08 06:18:29,972] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:18:30,640] {logging_mixin.py:109} INFO - [2022-08-08 06:18:30,638] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:18:30,659] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:18:30,674] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.709 seconds
[2022-08-08 06:19:01,284] {processor.py:163} INFO - Started process (PID=1562) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:19:01,288] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:19:01,290] {logging_mixin.py:109} INFO - [2022-08-08 06:19:01,290] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:19:02,073] {logging_mixin.py:109} INFO - [2022-08-08 06:19:02,070] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:19:02,088] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:19:02,100] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.822 seconds
[2022-08-08 06:19:32,187] {processor.py:163} INFO - Started process (PID=1625) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:19:32,189] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:19:32,190] {logging_mixin.py:109} INFO - [2022-08-08 06:19:32,190] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:19:32,873] {logging_mixin.py:109} INFO - [2022-08-08 06:19:32,871] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:19:32,888] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:19:32,897] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.714 seconds
[2022-08-08 06:20:03,033] {processor.py:163} INFO - Started process (PID=1695) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:20:03,034] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:20:03,036] {logging_mixin.py:109} INFO - [2022-08-08 06:20:03,036] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:20:03,718] {logging_mixin.py:109} INFO - [2022-08-08 06:20:03,716] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:20:03,734] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:20:03,742] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.715 seconds
[2022-08-08 06:20:33,814] {processor.py:163} INFO - Started process (PID=1761) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:20:33,816] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:20:33,818] {logging_mixin.py:109} INFO - [2022-08-08 06:20:33,818] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:20:34,515] {logging_mixin.py:109} INFO - [2022-08-08 06:20:34,513] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:20:34,534] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:20:34,544] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.734 seconds
[2022-08-08 06:21:05,116] {processor.py:163} INFO - Started process (PID=1830) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:21:05,119] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:21:05,120] {logging_mixin.py:109} INFO - [2022-08-08 06:21:05,120] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:21:05,760] {logging_mixin.py:109} INFO - [2022-08-08 06:21:05,758] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:21:05,774] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:21:05,783] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.671 seconds
[2022-08-08 06:21:36,622] {processor.py:163} INFO - Started process (PID=1890) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:21:36,625] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:21:36,626] {logging_mixin.py:109} INFO - [2022-08-08 06:21:36,626] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:21:37,386] {logging_mixin.py:109} INFO - [2022-08-08 06:21:37,384] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:21:37,405] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:21:37,394] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.799 seconds
[2022-08-08 06:22:07,453] {processor.py:163} INFO - Started process (PID=1959) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:22:07,456] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:22:07,458] {logging_mixin.py:109} INFO - [2022-08-08 06:22:07,457] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:22:08,057] {logging_mixin.py:109} INFO - [2022-08-08 06:22:08,055] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:22:08,072] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:22:08,082] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.635 seconds
[2022-08-08 06:22:39,006] {processor.py:163} INFO - Started process (PID=2019) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:22:39,009] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 06:22:39,011] {logging_mixin.py:109} INFO - [2022-08-08 06:22:39,011] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:22:39,879] {logging_mixin.py:109} INFO - [2022-08-08 06:22:39,877] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 06:22:39,896] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 06:22:39,907] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 0.905 seconds
[2022-08-08 07:11:41,920] {processor.py:163} INFO - Started process (PID=2048) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 07:11:41,925] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 07:11:41,928] {logging_mixin.py:109} INFO - [2022-08-08 07:11:41,928] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 07:11:43,411] {logging_mixin.py:109} INFO - [2022-08-08 07:11:43,401] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 07:11:43,443] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 07:11:43,453] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 1.592 seconds
[2022-08-08 09:12:18,875] {processor.py:163} INFO - Started process (PID=2105) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 09:12:18,925] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 09:12:19,077] {logging_mixin.py:109} INFO - [2022-08-08 09:12:19,066] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 09:12:21,322] {processor.py:163} INFO - Started process (PID=2113) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 09:12:21,326] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 09:12:21,331] {logging_mixin.py:109} INFO - [2022-08-08 09:12:21,331] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 09:12:24,969] {logging_mixin.py:109} INFO - [2022-08-08 09:12:24,964] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 09:12:25,001] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 09:12:25,017] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 3.723 seconds
[2022-08-08 09:16:09,694] {processor.py:163} INFO - Started process (PID=2144) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 09:16:09,698] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 09:16:09,701] {logging_mixin.py:109} INFO - [2022-08-08 09:16:09,701] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 09:16:11,169] {logging_mixin.py:109} INFO - [2022-08-08 09:16:11,167] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 09:16:11,200] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 09:16:11,216] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 1.526 seconds
[2022-08-08 09:16:53,978] {processor.py:163} INFO - Started process (PID=2199) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 09:16:54,678] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 09:16:54,878] {logging_mixin.py:109} INFO - [2022-08-08 09:16:54,875] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 09:32:31,943] {logging_mixin.py:109} INFO - [2022-08-08 09:32:31,942] {timeout.py:36} ERROR - Process timed out, PID: 2199
[2022-08-08 09:32:31,963] {logging_mixin.py:109} INFO - [2022-08-08 09:32:31,946] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 7, in <module>
    from google.cloud import storage
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/__init__.py", line 35, in <module>
    from google.cloud.storage.batch import Batch
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/batch.py", line 29, in <module>
    from google.cloud import _helpers
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_helpers.py", line 37, in <module>
    import grpc
  File "/home/airflow/.local/lib/python3.7/site-packages/grpc/__init__.py", line 2189, in <module>
    from grpc import aio  # pylint: disable=ungrouped-imports
  File "/home/airflow/.local/lib/python3.7/site-packages/grpc/aio/__init__.py", line 44, in <module>
    from ._call import AioRpcError
  File "/home/airflow/.local/lib/python3.7/site-packages/grpc/aio/_call.py", line 25, in <module>
    from grpc import _common
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 589, in module_from_spec
  File "<frozen importlib._bootstrap>", line 568, in _init_module_attrs
  File "<frozen importlib._bootstrap>", line 409, in cached
  File "<frozen importlib._bootstrap_external>", line 370, in _get_cached
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/gcs_to_bigquery.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 2199
[2022-08-08 09:32:32,062] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 09:32:32,103] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 940.041 seconds
[2022-08-08 09:32:33,817] {processor.py:163} INFO - Started process (PID=2220) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 09:32:33,828] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 09:32:33,839] {logging_mixin.py:109} INFO - [2022-08-08 09:32:33,838] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 09:32:40,394] {logging_mixin.py:109} INFO - [2022-08-08 09:32:40,375] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 13, in <module>
    from Airflow.dags.source_to_gcs import SourceToGCSOperator
ModuleNotFoundError: No module named 'Airflow'
[2022-08-08 09:32:40,492] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 09:32:40,557] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 6.794 seconds
[2022-08-08 09:34:42,571] {processor.py:163} INFO - Started process (PID=2279) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 09:34:42,662] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 09:34:42,711] {logging_mixin.py:109} INFO - [2022-08-08 09:34:42,667] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 09:35:12,851] {logging_mixin.py:109} INFO - [2022-08-08 09:35:12,814] {timeout.py:36} ERROR - Process timed out, PID: 2279
[2022-08-08 09:35:12,998] {logging_mixin.py:109} INFO - [2022-08-08 09:35:12,877] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 8, in <module>
    from airflow.providers.google.cloud.operators.bigquery import BigQueryCreateExternalTableOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 37, in <module>
    from airflow.operators.sql import SQLCheckOperator, SQLIntervalCheckOperator, SQLValueCheckOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/sql.py", line 18, in <module>
    from distutils.util import strtobool
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/gcs_to_bigquery.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 2279
[2022-08-08 09:35:13,741] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 09:35:14,288] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 31.893 seconds
[2022-08-08 09:44:14,358] {processor.py:163} INFO - Started process (PID=2354) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 09:44:14,404] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 09:44:14,449] {logging_mixin.py:109} INFO - [2022-08-08 09:44:14,449] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 09:58:47,012] {logging_mixin.py:109} INFO - [2022-08-08 09:58:47,008] {timeout.py:36} ERROR - Process timed out, PID: 2354
[2022-08-08 09:58:46,607] {logging_mixin.py:109} INFO - [2022-08-08 09:58:46,584] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 7, in <module>
    from google.cloud import storage
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/__init__.py", line 37, in <module>
    from google.cloud.storage.bucket import Bucket
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 917, in get_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/gcs_to_bigquery.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 2354
[2022-08-08 09:58:49,546] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 09:58:49,703] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 876.140 seconds
[2022-08-08 09:59:29,936] {processor.py:163} INFO - Started process (PID=2378) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 09:59:32,975] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 09:59:34,320] {logging_mixin.py:109} INFO - [2022-08-08 09:59:33,964] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 10:00:09,927] {logging_mixin.py:109} INFO - [2022-08-08 10:00:09,236] {timeout.py:36} ERROR - Process timed out, PID: 2378
[2022-08-08 10:15:29,204] {logging_mixin.py:109} INFO - [2022-08-08 10:00:10,806] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 7, in <module>
    from google.cloud import storage
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/__init__.py", line 35, in <module>
    from google.cloud.storage.batch import Batch
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/batch.py", line 29, in <module>
    from google.cloud import _helpers
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_helpers.py", line 33, in <module>
    from google.protobuf import duration_pb2
  File "/home/airflow/.local/lib/python3.7/site-packages/google/protobuf/duration_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/airflow/.local/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 40, in <module>
    from google.protobuf.internal import api_implementation
  File "/home/airflow/.local/lib/python3.7/site-packages/google/protobuf/internal/api_implementation.py", line 40, in <module>
    from google.protobuf.internal import _api_implementation
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/gcs_to_bigquery.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 2378
[2022-08-08 10:17:57,920] {processor.py:163} INFO - Started process (PID=2461) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 10:17:58,300] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 10:17:58,535] {logging_mixin.py:109} INFO - [2022-08-08 10:17:58,535] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 10:18:31,177] {logging_mixin.py:109} INFO - [2022-08-08 10:18:29,787] {timeout.py:36} ERROR - Process timed out, PID: 2461
[2022-08-08 10:19:13,445] {processor.py:163} INFO - Started process (PID=2506) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 10:19:13,913] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 10:19:14,814] {logging_mixin.py:109} INFO - [2022-08-08 10:19:14,476] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 10:19:50,244] {logging_mixin.py:109} INFO - [2022-08-08 10:19:49,357] {timeout.py:36} ERROR - Process timed out, PID: 2506
[2022-08-08 10:20:04,527] {logging_mixin.py:109} INFO - [2022-08-08 10:19:51,523] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 7, in <module>
    from google.cloud import storage
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/__init__.py", line 35, in <module>
    from google.cloud.storage.batch import Batch
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/batch.py", line 29, in <module>
    from google.cloud import _helpers
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_helpers.py", line 33, in <module>
    from google.protobuf import duration_pb2
  File "/home/airflow/.local/lib/python3.7/site-packages/google/protobuf/duration_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/airflow/.local/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
  File "/usr/local/lib/python3.7/abc.py", line 130, in register
    def register(cls, subclass):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/manager.py", line 496, in _exit_gracefully
    self.log.debug("Current Stacktrace is: %s", '\n'.join(map(str, inspect.stack())))
  File "/usr/local/lib/python3.7/inspect.py", line 1513, in stack
    return getouterframes(sys._getframe(1), context)
  File "/usr/local/lib/python3.7/inspect.py", line 1490, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File "/usr/local/lib/python3.7/inspect.py", line 1464, in getframeinfo
    lines, lnum = findsource(frame)
  File "/usr/local/lib/python3.7/inspect.py", line 780, in findsource
    module = getmodule(object, file)
  File "/usr/local/lib/python3.7/inspect.py", line 739, in getmodule
    f = getabsfile(module)
  File "/usr/local/lib/python3.7/inspect.py", line 708, in getabsfile
    _filename = getsourcefile(object) or getfile(object)
  File "/usr/local/lib/python3.7/inspect.py", line 693, in getsourcefile
    if os.path.exists(filename):
  File "/usr/local/lib/python3.7/genericpath.py", line 19, in exists
    os.stat(path)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/gcs_to_bigquery.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 2506
[2022-08-08 10:20:13,330] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 10:20:14,377] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 61.595 seconds
[2022-08-08 10:50:33,000] {processor.py:163} INFO - Started process (PID=2566) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 10:50:33,102] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 10:50:33,144] {logging_mixin.py:109} INFO - [2022-08-08 10:50:33,144] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 10:51:04,445] {logging_mixin.py:109} INFO - [2022-08-08 10:51:03,409] {timeout.py:36} ERROR - Process timed out, PID: 2566
[2022-08-08 10:51:17,545] {logging_mixin.py:109} INFO - [2022-08-08 10:51:05,106] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 7, in <module>
    from google.cloud import storage
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/__init__.py", line 35, in <module>
    from google.cloud.storage.batch import Batch
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/batch.py", line 29, in <module>
    from google.cloud import _helpers
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_helpers.py", line 37, in <module>
    import grpc
  File "/home/airflow/.local/lib/python3.7/site-packages/grpc/__init__.py", line 2189, in <module>
    from grpc import aio  # pylint: disable=ungrouped-imports
  File "/home/airflow/.local/lib/python3.7/site-packages/grpc/aio/__init__.py", line 44, in <module>
    from ._call import AioRpcError
  File "/home/airflow/.local/lib/python3.7/site-packages/grpc/aio/_call.py", line 535, in <module>
    class UnaryStreamCall(_StreamResponseMixin, Call, _base_call.UnaryStreamCall):
  File "/usr/local/lib/python3.7/abc.py", line 126, in __new__
    cls = super().__new__(mcls, name, bases, namespace, **kwargs)
  File "/usr/local/lib/python3.7/typing.py", line 849, in __init_subclass__
    def __init_subclass__(cls, *args, **kwargs):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/gcs_to_bigquery.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 2566
[2022-08-08 10:52:03,382] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 10:53:48,322] {processor.py:163} INFO - Started process (PID=2649) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 10:53:56,005] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 10:53:58,295] {logging_mixin.py:109} INFO - [2022-08-08 10:53:57,928] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 10:54:33,815] {logging_mixin.py:109} INFO - [2022-08-08 10:54:33,482] {timeout.py:36} ERROR - Process timed out, PID: 2649
[2022-08-08 10:54:37,081] {logging_mixin.py:109} INFO - [2022-08-08 10:54:36,303] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 7, in <module>
    from google.cloud import storage
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/__init__.py", line 35, in <module>
    from google.cloud.storage.batch import Batch
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/batch.py", line 29, in <module>
    from google.cloud import _helpers
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_helpers.py", line 33, in <module>
    from google.protobuf import duration_pb2
  File "/home/airflow/.local/lib/python3.7/site-packages/google/protobuf/duration_pb2.py", line 5, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/home/airflow/.local/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
  File "/usr/local/lib/python3.7/abc.py", line 130, in register
    def register(cls, subclass):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/dag_processing/manager.py", line 496, in _exit_gracefully
    self.log.debug("Current Stacktrace is: %s", '\n'.join(map(str, inspect.stack())))
  File "/usr/local/lib/python3.7/inspect.py", line 1513, in stack
    return getouterframes(sys._getframe(1), context)
  File "/usr/local/lib/python3.7/inspect.py", line 1490, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File "/usr/local/lib/python3.7/inspect.py", line 1464, in getframeinfo
    lines, lnum = findsource(frame)
  File "/usr/local/lib/python3.7/inspect.py", line 780, in findsource
    module = getmodule(object, file)
  File "/usr/local/lib/python3.7/inspect.py", line 742, in getmodule
    os.path.realpath(f)] = module.__name__
  File "/usr/local/lib/python3.7/posixpath.py", line 395, in realpath
    path, ok = _joinrealpath(filename[:0], filename, {})
  File "/usr/local/lib/python3.7/posixpath.py", line 429, in _joinrealpath
    if not islink(newpath):
  File "/usr/local/lib/python3.7/posixpath.py", line 171, in islink
    st = os.lstat(path)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/gcs_to_bigquery.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 2649
[2022-08-08 10:54:39,918] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 10:54:41,996] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 64.207 seconds
[2022-08-08 11:21:43,046] {processor.py:163} INFO - Started process (PID=2784) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 11:21:43,064] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 11:21:43,096] {logging_mixin.py:109} INFO - [2022-08-08 11:21:43,096] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 11:22:22,174] {logging_mixin.py:109} INFO - [2022-08-08 11:22:19,555] {timeout.py:36} ERROR - Process timed out, PID: 2784
[2022-08-08 11:27:15,189] {logging_mixin.py:109} WARNING - Exception ignored in: <function WeakKeyDictionary.__init__.<locals>.remove at 0x7ff8f86fcf80>
[2022-08-08 11:27:16,130] {logging_mixin.py:109} WARNING - Traceback (most recent call last):
[2022-08-08 11:27:42,378] {processor.py:163} INFO - Started process (PID=2822) to work on /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 11:27:42,517] {processor.py:642} INFO - Processing file /opt/airflow/dags/gcs_to_bigquery.py for tasks to queue
[2022-08-08 11:27:42,751] {logging_mixin.py:109} INFO - [2022-08-08 11:27:42,751] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 11:28:13,129] {logging_mixin.py:109} INFO - [2022-08-08 11:28:13,100] {timeout.py:36} ERROR - Process timed out, PID: 2822
[2022-08-08 11:28:14,371] {logging_mixin.py:109} INFO - [2022-08-08 11:28:13,446] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/gcs_to_bigquery.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gcs_to_bigquery.py", line 8, in <module>
    from airflow.providers.google.cloud.operators.bigquery import BigQueryCreateExternalTableOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/bigquery.py", line 38, in <module>
    from airflow.providers.google.cloud.hooks.bigquery import BigQueryHook, BigQueryJob
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/bigquery.py", line 33, in <module>
    from google.cloud.bigquery import (
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/__init__.py", line 35, in <module>
    from google.cloud.bigquery.client import Client
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery/client.py", line 61, in <module>
    from google.cloud.bigquery_storage_v1.services.big_query_read.client import (
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery_storage_v1/__init__.py", line 25, in <module>
    from google.cloud.bigquery_storage_v1 import client
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/bigquery_storage_v1/client.py", line 24, in <module>
    import google.api_core.gapic_v1.method
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/gapic_v1/__init__.py", line 18, in <module>
    from google.api_core.gapic_v1 import config
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 818, in get_code
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/timeout.py", line 37, in handle_timeout
    raise AirflowTaskTimeout(self.error_message)
airflow.exceptions.AirflowTaskTimeout: DagBag import timeout for /opt/airflow/dags/gcs_to_bigquery.py after 30.0s.
Please take a look at these docs to improve your DAG import time:
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#top-level-python-code
* https://airflow.apache.org/docs/apache-airflow/2.2.3/best-practices.html#reducing-dag-complexity, PID: 2822
[2022-08-08 11:28:15,499] {processor.py:656} WARNING - No viable dags retrieved from /opt/airflow/dags/gcs_to_bigquery.py
[2022-08-08 11:28:16,776] {processor.py:171} INFO - Processing /opt/airflow/dags/gcs_to_bigquery.py took 34.578 seconds
